
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 10;
  public static final int CADENA = 16;
  public static final int OR = 13;
  public static final int RCONJ = 2;
  public static final int CONCAT = 12;
  public static final int DPORCENTAJE = 9;
  public static final int POR = 8;
  public static final int LLAVEIZQ = 4;
  public static final int ALCANCE = 14;
  public static final int COMA = 15;
  public static final int ASIGNACION = 7;
  public static final int LLAVEDER = 5;
  public static final int EOF = 0;
  public static final int RLETRAMIN = 18;
  public static final int RLETRAMAY = 19;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 17;
  public static final int INTER = 11;
  public static final int MAS = 6;
  public static final int RNUMERO = 20;
  public static final int PTCOMA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RCONJ",
  "PTCOMA",
  "LLAVEIZQ",
  "LLAVEDER",
  "MAS",
  "ASIGNACION",
  "POR",
  "DPORCENTAJE",
  "DOSPUNTOS",
  "INTER",
  "CONCAT",
  "OR",
  "ALCANCE",
  "COMA",
  "CADENA",
  "IDENTIFICADOR",
  "RLETRAMIN",
  "RLETRAMAY",
  "RNUMERO"
  };
}

