
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 26;
  public static final int SPECIAL3 = 9;
  public static final int SPECIAL2 = 8;
  public static final int ALCANCE = 41;
  public static final int RLETRAMIN = 4;
  public static final int POR = 20;
  public static final int SPECIAL1 = 7;
  public static final int CONCAT = 24;
  public static final int GBAJO = 37;
  public static final int LLAVEDER = 40;
  public static final int RNUMERO = 6;
  public static final int PABIERTA = 18;
  public static final int IDENTIFICADOR = 3;
  public static final int IGUAL = 29;
  public static final int NUME = 13;
  public static final int OR = 39;
  public static final int ARROBA = 32;
  public static final int DIV = 25;
  public static final int CORCERRADO = 35;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMILLA = 12;
  public static final int COMA = 22;
  public static final int CADENA = 2;
  public static final int MENOS = 23;
  public static final int MENOR = 28;
  public static final int RLETRAMAY = 5;
  public static final int COMSIMPLE = 17;
  public static final int POTENCIA = 36;
  public static final int RCONJ = 10;
  public static final int FLECHA = 30;
  public static final int BARINVERTIDA = 34;
  public static final int ANDD = 16;
  public static final int LLAVEIZQ = 38;
  public static final int CORABIERTO = 33;
  public static final int PTCOMA = 27;
  public static final int PCERRADA = 19;
  public static final int DPORCENTAJE = 15;
  public static final int ADMI = 11;
  public static final int INTER = 31;
  public static final int DOLAR = 14;
  public static final int MAS = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "IDENTIFICADOR",
  "RLETRAMIN",
  "RLETRAMAY",
  "RNUMERO",
  "SPECIAL1",
  "SPECIAL2",
  "SPECIAL3",
  "RCONJ",
  "ADMI",
  "COMILLA",
  "NUME",
  "DOLAR",
  "DPORCENTAJE",
  "ANDD",
  "COMSIMPLE",
  "PABIERTA",
  "PCERRADA",
  "POR",
  "MAS",
  "COMA",
  "MENOS",
  "CONCAT",
  "DIV",
  "DOSPUNTOS",
  "PTCOMA",
  "MENOR",
  "IGUAL",
  "FLECHA",
  "INTER",
  "ARROBA",
  "CORABIERTO",
  "BARINVERTIDA",
  "CORCERRADO",
  "POTENCIA",
  "GBAJO",
  "LLAVEIZQ",
  "OR",
  "LLAVEDER",
  "ALCANCE"
  };
}

