
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 9;
  public static final int PUNTO = 4;
  public static final int GBAJO = 3;
  public static final int CADENA = 19;
  public static final int DOSPUNTOS = 13;
  public static final int DOLAR = 27;
  public static final int OR = 16;
  public static final int RCONJ = 2;
  public static final int FLECHA = 10;
  public static final int CONCAT = 15;
  public static final int NUME = 26;
  public static final int DPORCENTAJE = 12;
  public static final int POR = 11;
  public static final int LLAVEIZQ = 6;
  public static final int COMA = 18;
  public static final int ALCANCE = 17;
  public static final int ANDD = 28;
  public static final int LLAVEDER = 7;
  public static final int SIMBOLS = 29;
  public static final int EOF = 0;
  public static final int COMILLA = 25;
  public static final int RLETRAMIN = 21;
  public static final int RLETRAMAY = 22;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 20;
  public static final int INTER = 14;
  public static final int EARROBA = 30;
  public static final int ADMI = 24;
  public static final int MAS = 8;
  public static final int RNUMERO = 23;
  public static final int PTCOMA = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RCONJ",
  "GBAJO",
  "PUNTO",
  "PTCOMA",
  "LLAVEIZQ",
  "LLAVEDER",
  "MAS",
  "MENOS",
  "FLECHA",
  "POR",
  "DPORCENTAJE",
  "DOSPUNTOS",
  "INTER",
  "CONCAT",
  "OR",
  "ALCANCE",
  "COMA",
  "CADENA",
  "IDENTIFICADOR",
  "RLETRAMIN",
  "RLETRAMAY",
  "RNUMERO",
  "ADMI",
  "COMILLA",
  "NUME",
  "DOLAR",
  "ANDD",
  "SIMBOLS",
  "EARROBA"
  };
}

